<?php
/**
* Implements hook_block_info().
*/
function webhost_migrate_form_alter(&$form, &$form_state, $form_id) {
    // Add validation for a particular Webform node:
    if ($form_id == 'webform_client_form_8') {
      // Simply add the additional validate handler.
	  drupal_set_message(t('This is a test'),'status');
      $form['#validate'][] = 'webhost_migrate_validate_1';

      // Add the submit handler after the existing Webform submit handler,
      // but before the second Webform handler. Pop off the first one and add
      // ours second.
      $first = array_shift($form['#submit']);
      array_unshift($form['#submit'], $first, 'webhost_migrate_submit_1');
	  
    }
  }
  
 function _webhost_migrate_webform_component_mapping($node) {
    $mapping = array();
    $components = $node->webform['components'];
    foreach ($components as $i => $component) {
      $key = $component['form_key'];
      $mapping[$key] = $i;
    }
    return $mapping;
  }

  /**
  * Validation handler for Webform ID #44.
  */
  function webhost_migrate_validate_1(&$form, &$form_state) {
    global $user;
	/*
    if (!isset($user->roles[3])) {
      form_set_error('', t('Your user role is not allowed to submit this Webform.'));
    }
	$password = $submission->data[$mapping['password']]['value'][0];
	if ($password == 'test')
	{
		form_set_error('',t('Youre password is incorrect'));
		
	}
	*/
  }

  function webhost_migrate_webform_submission_presave($node,&$submission) {
	  $component_id = 1;
	  $submission->data[$component_id][0] = 'FOO';
	
	
  }
  /**
  * Submit handler for Webform ID #44.
  */
  function webhost_migrate_submit_1(&$form, &$form_state) {
    global $user;

    // Changes can be made to the Webform node settings by modifying this variable:
   // $form['#node']->webform;
    // Insert things into other database tables or modify properties.
  }
  
  function webhost_migrate_webform_submission_insert($node, $submission) {
    if ($node->nid == 8) {
      $mapping = _webhost_migrate_webform_component_mapping($node);
   
      $pass = $submission->data[$mapping['password']]['value'][0];
	  drupal_set_message(t($pass),'status');
    }
  }