<?php

/**
 * Implementation of hook_webform_component_info().
 */
function webform_password_webform_component_info() {
    return array(
        'password' => array(
            'label' => t('Password'),
            'description' => t('Basic Password textfield type.'),
            'file' => 'components/password.inc',
        )
    );
}

/**
 * Implementation of hook_webform_validator_alter().
 */
function webform_password_webform_validator_alter(&$validators) {
  // Provide the same validation rules as a textfield
  if ($validators) {
    foreach ($validators as $validator_name => $validator_info) {
      if (in_array('textfield', $validator_info['component_types'])) {
        $validators[$validator_name]['component_types'][] = 'password';
      }
    }
  }
}